open up Mapped.__set__ for mypy 1.2
We are getting errors in 1.4 mypy due to the Mapped.__set__ method
being too specific in some way:

    [classic@photon3 sqlalchemy:rel_1_4]$ PYTHONPATH=~/dev/sqlalchemy/lib/:~/dev/sqlalchemy2-stubs/ mypy test/ext/mypy/files/dataclasses_workaround.py
    test/ext/mypy/files/dataclasses_workaround.py:34: error: Unsupported "__set__" in "Mapped"  [misc]
    test/ext/mypy/files/dataclasses_workaround.py:35: error: Unsupported "__set__" in "Mapped"  [misc]
    test/ext/mypy/files/dataclasses_workaround.py:36: error: Unsupported "__set__" in "Mapped"  [misc]
    test/ext/mypy/files/dataclasses_workaround.py:37: error: Unsupported "__set__" in "Mapped"  [misc]
    test/ext/mypy/files/dataclasses_workaround.py:38: error: Unsupported "__set__" in "Mapped"  [misc]
    test/ext/mypy/files/dataclasses_workaround.py:59: error: Unsupported "__set__" in "Mapped"  [misc]
    test/ext/mypy/files/dataclasses_workaround.py:60: error: Unsupported "__set__" in "Mapped"  [misc]
    test/ext/mypy/files/dataclasses_workaround.py:61: error: Unsupported "__set__" in "Mapped"  [misc]
    Found 8 errors in 1 file (checked 1 source file)

Open this up to avoid errors.